name: animation
description: A new Flutter project.

# The version of your application
version: 1.0.0+1

# Add the environment section for SDK constraint
environment:
  sdk: '>=2.12.0 <3.5.5'

dependencies:
  flutter:
    sdk: flutter

  # Add any other dependencies here
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true